### ISSUE TITLE
Proposition de champs supplémentaires (type eau et source)

### ISSUE THREAD

**Issue by mikoa9** [datagouv/schema-fontaine-eau#1]
nouveaux champs possibles :

- type/caractéristique de l'eau --> ex :  gazeuse ou plate (info : https://eau.selectra.info/eau-de-paris/fontaines-eau-potable/gazeuse)
- source de l'eau --> ex :  Nappe de l'Albien du bassin de Paris

Clarisse

**Comment by Pierlou** [comment]
Il ne s'agit que de fontaines au sein d'ERP, avec raccordement à l'eau courante, donc champs non-applicables :/
